$replacements = @{
  "C�cile" = "Cécile"
  "�tude" = "Étude"
  "�tudes" = "Études"
  "� propos" = "À propos"
  "�quipe" = "équipe"
  "�crans" = "Écrans"
  "�cran" = "écran"
  "�ditorial" = "Éditorial"
  "�ditoriale" = "éditoriale"
  "Publicit�" = "Publicité"
  "diversit�" = "diversité"
  "sant�" = "santé"
  "apr�s" = "après"
  "num�riques" = "numériques"
  "centr�es" = "centrées"
  "m�thodique" = "méthodique"
  "m�thodes" = "méthodes"
  "m�thode" = "méthode"
  "�coute" = "écoute"
  "d�marche" = "démarche"
  "comp�tences" = "compétences"
  "r�els" = "réels"
  "r�servation" = "réservation"
  "r�server" = "réserver"
  "r�alis�s" = "réalisés"
  "r�currente" = "récurrente"
  "cr�er" = "créer"
  "Cr�ation" = "Création"
  "id�es" = "idées"
  "d�couverte" = "découverte"
  "d�di�e" = "dédiée"
  "pens�e" = "pensée"
  "gr�ce" = "grâce"
  "R�le" = "Rôle"
  "responsabilit�s" = "responsabilités"
  "Synth�se" = "Synthèse"
  "Probl�matique" = "Problématique"
  "It�rations" = "Itérations"
  "cl�s" = "clés"
  "am�lioration" = "amélioration"
  "r�pondre" = "répondre"
  "d�finir" = "définir"
  "g�rant" = "gérant"
  "exp�riences" = "expériences"
  "exp�riment�s" = "expérimentés"
  "compr�hension" = "compréhension"
  "compr�hensibles" = "compréhensibles"
  "priorit�s" = "priorités"
  "d�tails" = "détails"
  "strat�gique" = "stratégique"
  "Structur�e" = "Structurée"
  "structur�s" = "structurés"
  "refl�te" = "reflète"
  "r�servations" = "réservations"
  "�changer" = "échanger"
  "d'�" = "d’é"
  "l'�" = "l’é"
  "� <span data-year>" = "© <span data-year>"
}

$files = Get-ChildItem -Path "C:\Users\cilro\Documents\UI designer\Portfolio\*.html"
foreach ($file in $files) {
  $text = Get-Content -Raw -Encoding UTF8 $file.FullName
  foreach ($k in $replacements.Keys) {
    $text = $text.Replace($k, $replacements[$k])
  }
  Set-Content -Path $file.FullName -Value $text -Encoding UTF8
}
